### ISSUE TITLE
A. Parenthesis

### ISSUE THREAD

**Issue by npnorman** [Eagle-9/crash#127]
A pair of parenthesis indicates a subshell. A set of commands in the parenthesis are executed in a
subshell environment so that variable assignments and `builtin` commands that affect the shell’s
environment do not remain in effect after the command completes. For example, let me assume that the
following script is executed in `/home/user` directory.
```
pwd
( cd temp; pwd )
pwd
```
The script will print
```
/home/user
/home/user/temp
/home/user
```

**Comment by dennorak** [comment]
@Derp88 I think we can do this by running the commands as `crach <commands>`, kinda like how we're running scripts and such now
