### ISSUE TITLE
extra space after comment & no ">>>" after comment

### ISSUE THREAD

**Issue by npnorman** [Eagle-9/crash#13]
after using a comment (`#`) and a new line (`\`) the following happens
```
$ #hello world\

$
```
similarly, when just using a # comment,
```
$ #hello world\

$
```
I believe this should be
```
$ #hello world\
>>> 
```
and respectively
```
$ #hello world\
$
```

**Comment by Derp88** [comment]
I think case 2 of this issue has been solved but case 1 is still broken.

``$ #hello world\``

Does not have a continuation/accept anything after the comment. Instead it returns nothing.
Tested with Project release 1, and most recent version of master.

**Comment by dennorak** [comment]
@Derp88 that's because a line that's just ' ' is a blank line, and is ignored
