### ISSUE TITLE
Extra prompt is printed when processing files.

### ISSUE THREAD

**Issue by Derp88** [Eagle-9/crash#132]
Right now CRASH prints out a prompt whenever a file is ran. This isn't good because it often leads to duplicate prompts being displayed after execution. For example when using the `source` command the prompt is displayed twice. This is because there is a prompt for the execution of the line (ex: `source test.txt`), and then a second prompt for the execution of the file, `test.txt`.

In general, we shouldn't print a prompt if processing a file. I have the fix for this.

**Comment by sheepman39** [comment]
Closed #133
