### ISSUE TITLE
Incorrect keys in dict

### ISSUE THREAD

**Issue by dennorak** [Eagle-9/crash#26]
The dict categories need to be swapped for the list of keywords (and such) from the assignment, see #18 for the lists copied from the assignment

sidenote: I thought of this after merging, or I would've just told you on the pull request

**Comment by sheepman39** [comment]
The keywords form the assignment were added, so just remove the stuff from A1?  Want to clarify before continuing.

**Comment by dennorak** [comment]
i see you added them as well, do we need all the categories? Also, there's a key with two values

**Comment by dennorak** [comment]
Although we do need to look into how we're storing the functions for these

**Comment by sheepman39** [comment]
I think we just need internal / keywords?

Which one has duplicate?

**Comment by sheepman39** [comment]
TODO: Redo all of this into a struct with table inserting and whatnot as in lecture
