### ISSUE TITLE
CD Internal Command

### ISSUE THREAD

**Issue by Derp88** [Eagle-9/crash#41]
I haven't seen an actual issue for the core of the CD command, actually changing our working directory. So, here it is.

Resources:
https://stackoverflow.com/questions/25944172/changing-a-processs-current-working-directory-programmatically

> Change the current directory to DIR. The default DIR is the current directory so that it is identical to the pwd command in typical Linux shells.

**Comment by npnorman** [comment]
- [ ] check in `builtin_cd(...)` for a path (DIR)
- [ ] change directory using c `chdir(char* path)`
