### ISSUE TITLE
Implement Batch Mode

### ISSUE THREAD

**Issue by Derp88** [Eagle-9/crash#57]
We need to be able to run scripts in batch mode in 3 different ways.

- [x] Using script indirection, `$ beta < hello.psh`
- [x] As an argument, `$ beta hello.psh`
- [x] As the first line of a script, `#!PATHNAMEOFCRASH` in script and then as `$ hello.psh` in native terminal.

**Comment by dennorak** [comment]
duplicate #15

**Comment by dennorak** [comment]
reopening as requirements are different from the other issue

**Comment by Derp88** [comment]
This is working now, but I'm not sure if we actually use indirection correctly. CRASH sees `$ beta < hello.psh` as the same thing as `$ beta hello.psh`. It works (the delimiter just gets rid of the < basically), but I'm not sure if that is what the requirements want.

**Comment by dennorak** [comment]
> This is working now, but I'm not sure if we actually use indirection correctly. CRASH sees `$ beta < hello.psh` as the same thing as `$ beta hello.psh`. It works (the delimiter just gets rid of the < basically), but I'm not sure if that is what the requirements want.

This is normal, they're really only technically different. One passes the script path as an argument, the other passes the contents to stdin

**Comment by dennorak** [comment]
Also, the second two are weird to implement because of the pathing of the programs. This would be easier if the program was installed to a known location

**Comment by Derp88** [comment]
This is actually implemented before my changes. I misunderstood the project requirements.
