### ISSUE TITLE
Multi digit numbers

### ISSUE THREAD

**Issue by sheepman39** [Eagle-9/crash#63]
As of now, we can only support numerical inputs 0-9 since we only check and convert one digit in our cd command.  Medium priority if anyone has any ideas.

**Comment by Derp88** [comment]
Checkout d2ca467 for a potential solution. I don't love it, but I don't know how to find the actual size of the inner array that contains all the numbers. It works, as long as someone doesn't need to go over 10 digits worth of history.

**Comment by Derp88** [comment]
Did a little test, as long as the number we are checking for the size of the number array is under 55,360 it works. If you go to 55,360 or above, you will get a seg fault.

**Comment by sheepman39** [comment]
I'm still getting errors on -n. I'll check it out more when I am free.

**Comment by Derp88** [comment]
Line 589 needs switched over to using atoi as well.
