### ISSUE TITLE
Shell Flags/Settings

### ISSUE THREAD

**Issue by sheepman39** [Eagle-9/crash#94]
Now that the base of the set command is done, we need to add flags for kill on error and a debug flag.  This can be done with the -t for errors and -v for debug.

**Comment by sheepman39** [comment]
Will wait until #93 is finished before starting in case critical changes are made.

**Comment by dennorak** [comment]
@sheepman39 this is ready to work on now

**Comment by dennorak** [comment]
Make sure all current debug printing is moved to this flag btw

**Comment by sheepman39** [comment]
I'll take a look at this tomorrow.
